### PR TITLE
Update HTTP/2 images

### PR DESCRIPTION
**Pull request by flaudisio**
In a nutshell:

- "cosmetic" changes;
- Installation fixes/optimizations;
- nginx v1.9.5.

Let me know if there are any problems :smile:

### CODE REVIEW

**Comment by gabriellhrn** [comment]
Great improvements! 

That new version of Nginx already comes with the HTTP/2 patch, right? Could you please update your PR removing the `patch` package from the Nginx Dockerfile?

**Comment by gabriellhrn** [comment]
The commit b6cc594 was merged. Thanks for the fix.

**Comment by flaudisio** [comment]
Done! Thanks for spotting that.

**Comment by gabriellhrn** [comment]
Thanks for the contribution!

**Pull request merged**
